# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Configuration.proto

require 'google/protobuf'


descriptor_data = "\n\x13\x43onfiguration.proto\"{\n\rConfiguration\x12\x1d\n\x15\x66\x61ult_tolerance_level\x18\x01 \x01(\x05\x12)\n\x06method\x18\x02 \x01(\x0e\x32\x19.Configuration.MethodType\" \n\nMethodType\x12\x08\n\x04STRT\x10\x00\x12\x08\n\x04STOP\x10\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Configuration").msgclass
Configuration::MethodType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Configuration.MethodType").enummodule
