# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

require 'google/protobuf'


descriptor_data = "\n\rMessage.proto\"\xa6\x01\n\x07Message\x12#\n\x06\x64\x65mand\x18\x01 \x01(\x0e\x32\x13.Message.DemandType\x12\'\n\x08response\x18\x02 \x01(\x0e\x32\x15.Message.ResponseType\"+\n\nDemandType\x12\t\n\x05\x43PCTY\x10\x00\x12\x08\n\x04STRT\x10\x01\x12\x08\n\x04STOP\x10\x02\" \n\x0cResponseType\x12\x07\n\x03YEP\x10\x00\x12\x07\n\x03NOP\x10\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Message").msgclass
Message::DemandType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Message.DemandType").enummodule
Message::ResponseType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Message.ResponseType").enummodule
