// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Message.proto
// Protobuf Java Version: 4.29.3

public final class MessageOuterClass {
  private MessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * İstek türü
     * </pre>
     *
     * <code>.Message.DemandType demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    int getDemandValue();
    /**
     * <pre>
     * İstek türü
     * </pre>
     *
     * <code>.Message.DemandType demand = 1;</code>
     * @return The demand.
     */
    MessageOuterClass.Message.DemandType getDemand();

    /**
     * <pre>
     * Yanıt türü
     * </pre>
     *
     * <code>.Message.ResponseType response = 2;</code>
     * @return The enum numeric value on the wire for response.
     */
    int getResponseValue();
    /**
     * <pre>
     * Yanıt türü
     * </pre>
     *
     * <code>.Message.ResponseType response = 2;</code>
     * @return The response.
     */
    MessageOuterClass.Message.ResponseType getResponse();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      demand_ = 0;
      response_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageOuterClass.Message.class, MessageOuterClass.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code Message.DemandType}
     */
    public enum DemandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Kapasite sorgusu
       * </pre>
       *
       * <code>CPCTY = 0;</code>
       */
      CPCTY(0),
      /**
       * <pre>
       * Başlatma
       * </pre>
       *
       * <code>STRT = 1;</code>
       */
      STRT(1),
      /**
       * <pre>
       * Durdurma
       * </pre>
       *
       * <code>STOP = 2;</code>
       */
      STOP(2),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 3,
          /* suffix= */ "",
          DemandType.class.getName());
      }
      /**
       * <pre>
       * Kapasite sorgusu
       * </pre>
       *
       * <code>CPCTY = 0;</code>
       */
      public static final int CPCTY_VALUE = 0;
      /**
       * <pre>
       * Başlatma
       * </pre>
       *
       * <code>STRT = 1;</code>
       */
      public static final int STRT_VALUE = 1;
      /**
       * <pre>
       * Durdurma
       * </pre>
       *
       * <code>STOP = 2;</code>
       */
      public static final int STOP_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DemandType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DemandType forNumber(int value) {
        switch (value) {
          case 0: return CPCTY;
          case 1: return STRT;
          case 2: return STOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DemandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DemandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DemandType>() {
              public DemandType findValueByNumber(int number) {
                return DemandType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageOuterClass.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final DemandType[] VALUES = values();

      public static DemandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DemandType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.DemandType)
    }

    /**
     * Protobuf enum {@code Message.ResponseType}
     */
    public enum ResponseType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Olumlu yanıt
       * </pre>
       *
       * <code>YEP = 0;</code>
       */
      YEP(0),
      /**
       * <pre>
       * Olumsuz yanıt
       * </pre>
       *
       * <code>NOP = 1;</code>
       */
      NOP(1),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 3,
          /* suffix= */ "",
          ResponseType.class.getName());
      }
      /**
       * <pre>
       * Olumlu yanıt
       * </pre>
       *
       * <code>YEP = 0;</code>
       */
      public static final int YEP_VALUE = 0;
      /**
       * <pre>
       * Olumsuz yanıt
       * </pre>
       *
       * <code>NOP = 1;</code>
       */
      public static final int NOP_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ResponseType forNumber(int value) {
        switch (value) {
          case 0: return YEP;
          case 1: return NOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResponseType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
              public ResponseType findValueByNumber(int number) {
                return ResponseType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageOuterClass.Message.getDescriptor().getEnumTypes().get(1);
      }

      private static final ResponseType[] VALUES = values();

      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResponseType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.ResponseType)
    }

    public static final int DEMAND_FIELD_NUMBER = 1;
    private int demand_ = 0;
    /**
     * <pre>
     * İstek türü
     * </pre>
     *
     * <code>.Message.DemandType demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    @java.lang.Override public int getDemandValue() {
      return demand_;
    }
    /**
     * <pre>
     * İstek türü
     * </pre>
     *
     * <code>.Message.DemandType demand = 1;</code>
     * @return The demand.
     */
    @java.lang.Override public MessageOuterClass.Message.DemandType getDemand() {
      MessageOuterClass.Message.DemandType result = MessageOuterClass.Message.DemandType.forNumber(demand_);
      return result == null ? MessageOuterClass.Message.DemandType.UNRECOGNIZED : result;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private int response_ = 0;
    /**
     * <pre>
     * Yanıt türü
     * </pre>
     *
     * <code>.Message.ResponseType response = 2;</code>
     * @return The enum numeric value on the wire for response.
     */
    @java.lang.Override public int getResponseValue() {
      return response_;
    }
    /**
     * <pre>
     * Yanıt türü
     * </pre>
     *
     * <code>.Message.ResponseType response = 2;</code>
     * @return The response.
     */
    @java.lang.Override public MessageOuterClass.Message.ResponseType getResponse() {
      MessageOuterClass.Message.ResponseType result = MessageOuterClass.Message.ResponseType.forNumber(response_);
      return result == null ? MessageOuterClass.Message.ResponseType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (demand_ != MessageOuterClass.Message.DemandType.CPCTY.getNumber()) {
        output.writeEnum(1, demand_);
      }
      if (response_ != MessageOuterClass.Message.ResponseType.YEP.getNumber()) {
        output.writeEnum(2, response_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (demand_ != MessageOuterClass.Message.DemandType.CPCTY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, demand_);
      }
      if (response_ != MessageOuterClass.Message.ResponseType.YEP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageOuterClass.Message)) {
        return super.equals(obj);
      }
      MessageOuterClass.Message other = (MessageOuterClass.Message) obj;

      if (demand_ != other.demand_) return false;
      if (response_ != other.response_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEMAND_FIELD_NUMBER;
      hash = (53 * hash) + demand_;
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + response_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MessageOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MessageOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        MessageOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageOuterClass.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageOuterClass.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageOuterClass.Message.class, MessageOuterClass.Message.Builder.class);
      }

      // Construct using MessageOuterClass.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        demand_ = 0;
        response_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageOuterClass.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public MessageOuterClass.Message getDefaultInstanceForType() {
        return MessageOuterClass.Message.getDefaultInstance();
      }

      @java.lang.Override
      public MessageOuterClass.Message build() {
        MessageOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessageOuterClass.Message buildPartial() {
        MessageOuterClass.Message result = new MessageOuterClass.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MessageOuterClass.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.demand_ = demand_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.response_ = response_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageOuterClass.Message) {
          return mergeFrom((MessageOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageOuterClass.Message other) {
        if (other == MessageOuterClass.Message.getDefaultInstance()) return this;
        if (other.demand_ != 0) {
          setDemandValue(other.getDemandValue());
        }
        if (other.response_ != 0) {
          setResponseValue(other.getResponseValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                demand_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                response_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int demand_ = 0;
      /**
       * <pre>
       * İstek türü
       * </pre>
       *
       * <code>.Message.DemandType demand = 1;</code>
       * @return The enum numeric value on the wire for demand.
       */
      @java.lang.Override public int getDemandValue() {
        return demand_;
      }
      /**
       * <pre>
       * İstek türü
       * </pre>
       *
       * <code>.Message.DemandType demand = 1;</code>
       * @param value The enum numeric value on the wire for demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemandValue(int value) {
        demand_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İstek türü
       * </pre>
       *
       * <code>.Message.DemandType demand = 1;</code>
       * @return The demand.
       */
      @java.lang.Override
      public MessageOuterClass.Message.DemandType getDemand() {
        MessageOuterClass.Message.DemandType result = MessageOuterClass.Message.DemandType.forNumber(demand_);
        return result == null ? MessageOuterClass.Message.DemandType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * İstek türü
       * </pre>
       *
       * <code>.Message.DemandType demand = 1;</code>
       * @param value The demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemand(MessageOuterClass.Message.DemandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        demand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İstek türü
       * </pre>
       *
       * <code>.Message.DemandType demand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDemand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        demand_ = 0;
        onChanged();
        return this;
      }

      private int response_ = 0;
      /**
       * <pre>
       * Yanıt türü
       * </pre>
       *
       * <code>.Message.ResponseType response = 2;</code>
       * @return The enum numeric value on the wire for response.
       */
      @java.lang.Override public int getResponseValue() {
        return response_;
      }
      /**
       * <pre>
       * Yanıt türü
       * </pre>
       *
       * <code>.Message.ResponseType response = 2;</code>
       * @param value The enum numeric value on the wire for response to set.
       * @return This builder for chaining.
       */
      public Builder setResponseValue(int value) {
        response_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Yanıt türü
       * </pre>
       *
       * <code>.Message.ResponseType response = 2;</code>
       * @return The response.
       */
      @java.lang.Override
      public MessageOuterClass.Message.ResponseType getResponse() {
        MessageOuterClass.Message.ResponseType result = MessageOuterClass.Message.ResponseType.forNumber(response_);
        return result == null ? MessageOuterClass.Message.ResponseType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Yanıt türü
       * </pre>
       *
       * <code>.Message.ResponseType response = 2;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(MessageOuterClass.Message.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        response_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Yanıt türü
       * </pre>
       *
       * <code>.Message.ResponseType response = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final MessageOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageOuterClass.Message();
    }

    public static MessageOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessageOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"\246\001\n\007Message\022#\n\006demand\030\001 " +
      "\001(\0162\023.Message.DemandType\022\'\n\010response\030\002 \001" +
      "(\0162\025.Message.ResponseType\"+\n\nDemandType\022" +
      "\t\n\005CPCTY\020\000\022\010\n\004STRT\020\001\022\010\n\004STOP\020\002\" \n\014Respon" +
      "seType\022\007\n\003YEP\020\000\022\007\n\003NOP\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Demand", "Response", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
