// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SyncMessage.proto
// Protobuf Java Version: 4.29.3

public final class SyncMessageOuterClass {
  private SyncMessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      SyncMessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SyncMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Sunucu ID'si
     * </pre>
     *
     * <code>int32 server_id = 1;</code>
     * @return The serverId.
     */
    int getServerId();

    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    java.util.List<SyncMessageOuterClass.Subscriber> 
        getSubscribersList();
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    SyncMessageOuterClass.Subscriber getSubscribers(int index);
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    int getSubscribersCount();
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    java.util.List<? extends SyncMessageOuterClass.SubscriberOrBuilder> 
        getSubscribersOrBuilderList();
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    SyncMessageOuterClass.SubscriberOrBuilder getSubscribersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SyncMessage}
   */
  public static final class SyncMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SyncMessage)
      SyncMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SyncMessage.class.getName());
    }
    // Use SyncMessage.newBuilder() to construct.
    private SyncMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SyncMessage() {
      subscribers_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SyncMessageOuterClass.internal_static_SyncMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SyncMessageOuterClass.internal_static_SyncMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SyncMessageOuterClass.SyncMessage.class, SyncMessageOuterClass.SyncMessage.Builder.class);
    }

    public static final int SERVER_ID_FIELD_NUMBER = 1;
    private int serverId_ = 0;
    /**
     * <pre>
     * Sunucu ID'si
     * </pre>
     *
     * <code>int32 server_id = 1;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public int getServerId() {
      return serverId_;
    }

    public static final int SUBSCRIBERS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<SyncMessageOuterClass.Subscriber> subscribers_;
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    @java.lang.Override
    public java.util.List<SyncMessageOuterClass.Subscriber> getSubscribersList() {
      return subscribers_;
    }
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends SyncMessageOuterClass.SubscriberOrBuilder> 
        getSubscribersOrBuilderList() {
      return subscribers_;
    }
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    @java.lang.Override
    public int getSubscribersCount() {
      return subscribers_.size();
    }
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    @java.lang.Override
    public SyncMessageOuterClass.Subscriber getSubscribers(int index) {
      return subscribers_.get(index);
    }
    /**
     * <pre>
     * Abone listesi
     * </pre>
     *
     * <code>repeated .Subscriber subscribers = 2;</code>
     */
    @java.lang.Override
    public SyncMessageOuterClass.SubscriberOrBuilder getSubscribersOrBuilder(
        int index) {
      return subscribers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverId_ != 0) {
        output.writeInt32(1, serverId_);
      }
      for (int i = 0; i < subscribers_.size(); i++) {
        output.writeMessage(2, subscribers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      for (int i = 0; i < subscribers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, subscribers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SyncMessageOuterClass.SyncMessage)) {
        return super.equals(obj);
      }
      SyncMessageOuterClass.SyncMessage other = (SyncMessageOuterClass.SyncMessage) obj;

      if (getServerId()
          != other.getServerId()) return false;
      if (!getSubscribersList()
          .equals(other.getSubscribersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      if (getSubscribersCount() > 0) {
        hash = (37 * hash) + SUBSCRIBERS_FIELD_NUMBER;
        hash = (53 * hash) + getSubscribersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SyncMessageOuterClass.SyncMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SyncMessageOuterClass.SyncMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SyncMessageOuterClass.SyncMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SyncMessageOuterClass.SyncMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SyncMessageOuterClass.SyncMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SyncMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SyncMessage)
        SyncMessageOuterClass.SyncMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SyncMessageOuterClass.internal_static_SyncMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SyncMessageOuterClass.internal_static_SyncMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SyncMessageOuterClass.SyncMessage.class, SyncMessageOuterClass.SyncMessage.Builder.class);
      }

      // Construct using SyncMessageOuterClass.SyncMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serverId_ = 0;
        if (subscribersBuilder_ == null) {
          subscribers_ = java.util.Collections.emptyList();
        } else {
          subscribers_ = null;
          subscribersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SyncMessageOuterClass.internal_static_SyncMessage_descriptor;
      }

      @java.lang.Override
      public SyncMessageOuterClass.SyncMessage getDefaultInstanceForType() {
        return SyncMessageOuterClass.SyncMessage.getDefaultInstance();
      }

      @java.lang.Override
      public SyncMessageOuterClass.SyncMessage build() {
        SyncMessageOuterClass.SyncMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SyncMessageOuterClass.SyncMessage buildPartial() {
        SyncMessageOuterClass.SyncMessage result = new SyncMessageOuterClass.SyncMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(SyncMessageOuterClass.SyncMessage result) {
        if (subscribersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            subscribers_ = java.util.Collections.unmodifiableList(subscribers_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.subscribers_ = subscribers_;
        } else {
          result.subscribers_ = subscribersBuilder_.build();
        }
      }

      private void buildPartial0(SyncMessageOuterClass.SyncMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverId_ = serverId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SyncMessageOuterClass.SyncMessage) {
          return mergeFrom((SyncMessageOuterClass.SyncMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SyncMessageOuterClass.SyncMessage other) {
        if (other == SyncMessageOuterClass.SyncMessage.getDefaultInstance()) return this;
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (subscribersBuilder_ == null) {
          if (!other.subscribers_.isEmpty()) {
            if (subscribers_.isEmpty()) {
              subscribers_ = other.subscribers_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSubscribersIsMutable();
              subscribers_.addAll(other.subscribers_);
            }
            onChanged();
          }
        } else {
          if (!other.subscribers_.isEmpty()) {
            if (subscribersBuilder_.isEmpty()) {
              subscribersBuilder_.dispose();
              subscribersBuilder_ = null;
              subscribers_ = other.subscribers_;
              bitField0_ = (bitField0_ & ~0x00000002);
              subscribersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSubscribersFieldBuilder() : null;
            } else {
              subscribersBuilder_.addAllMessages(other.subscribers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                serverId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                SyncMessageOuterClass.Subscriber m =
                    input.readMessage(
                        SyncMessageOuterClass.Subscriber.parser(),
                        extensionRegistry);
                if (subscribersBuilder_ == null) {
                  ensureSubscribersIsMutable();
                  subscribers_.add(m);
                } else {
                  subscribersBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int serverId_ ;
      /**
       * <pre>
       * Sunucu ID'si
       * </pre>
       *
       * <code>int32 server_id = 1;</code>
       * @return The serverId.
       */
      @java.lang.Override
      public int getServerId() {
        return serverId_;
      }
      /**
       * <pre>
       * Sunucu ID'si
       * </pre>
       *
       * <code>int32 server_id = 1;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {

        serverId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sunucu ID'si
       * </pre>
       *
       * <code>int32 server_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<SyncMessageOuterClass.Subscriber> subscribers_ =
        java.util.Collections.emptyList();
      private void ensureSubscribersIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          subscribers_ = new java.util.ArrayList<SyncMessageOuterClass.Subscriber>(subscribers_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          SyncMessageOuterClass.Subscriber, SyncMessageOuterClass.Subscriber.Builder, SyncMessageOuterClass.SubscriberOrBuilder> subscribersBuilder_;

      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public java.util.List<SyncMessageOuterClass.Subscriber> getSubscribersList() {
        if (subscribersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subscribers_);
        } else {
          return subscribersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public int getSubscribersCount() {
        if (subscribersBuilder_ == null) {
          return subscribers_.size();
        } else {
          return subscribersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public SyncMessageOuterClass.Subscriber getSubscribers(int index) {
        if (subscribersBuilder_ == null) {
          return subscribers_.get(index);
        } else {
          return subscribersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder setSubscribers(
          int index, SyncMessageOuterClass.Subscriber value) {
        if (subscribersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscribersIsMutable();
          subscribers_.set(index, value);
          onChanged();
        } else {
          subscribersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder setSubscribers(
          int index, SyncMessageOuterClass.Subscriber.Builder builderForValue) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          subscribers_.set(index, builderForValue.build());
          onChanged();
        } else {
          subscribersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder addSubscribers(SyncMessageOuterClass.Subscriber value) {
        if (subscribersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscribersIsMutable();
          subscribers_.add(value);
          onChanged();
        } else {
          subscribersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder addSubscribers(
          int index, SyncMessageOuterClass.Subscriber value) {
        if (subscribersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscribersIsMutable();
          subscribers_.add(index, value);
          onChanged();
        } else {
          subscribersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder addSubscribers(
          SyncMessageOuterClass.Subscriber.Builder builderForValue) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          subscribers_.add(builderForValue.build());
          onChanged();
        } else {
          subscribersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder addSubscribers(
          int index, SyncMessageOuterClass.Subscriber.Builder builderForValue) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          subscribers_.add(index, builderForValue.build());
          onChanged();
        } else {
          subscribersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder addAllSubscribers(
          java.lang.Iterable<? extends SyncMessageOuterClass.Subscriber> values) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subscribers_);
          onChanged();
        } else {
          subscribersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder clearSubscribers() {
        if (subscribersBuilder_ == null) {
          subscribers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          subscribersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public Builder removeSubscribers(int index) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          subscribers_.remove(index);
          onChanged();
        } else {
          subscribersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public SyncMessageOuterClass.Subscriber.Builder getSubscribersBuilder(
          int index) {
        return getSubscribersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public SyncMessageOuterClass.SubscriberOrBuilder getSubscribersOrBuilder(
          int index) {
        if (subscribersBuilder_ == null) {
          return subscribers_.get(index);  } else {
          return subscribersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public java.util.List<? extends SyncMessageOuterClass.SubscriberOrBuilder> 
           getSubscribersOrBuilderList() {
        if (subscribersBuilder_ != null) {
          return subscribersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subscribers_);
        }
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public SyncMessageOuterClass.Subscriber.Builder addSubscribersBuilder() {
        return getSubscribersFieldBuilder().addBuilder(
            SyncMessageOuterClass.Subscriber.getDefaultInstance());
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public SyncMessageOuterClass.Subscriber.Builder addSubscribersBuilder(
          int index) {
        return getSubscribersFieldBuilder().addBuilder(
            index, SyncMessageOuterClass.Subscriber.getDefaultInstance());
      }
      /**
       * <pre>
       * Abone listesi
       * </pre>
       *
       * <code>repeated .Subscriber subscribers = 2;</code>
       */
      public java.util.List<SyncMessageOuterClass.Subscriber.Builder> 
           getSubscribersBuilderList() {
        return getSubscribersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          SyncMessageOuterClass.Subscriber, SyncMessageOuterClass.Subscriber.Builder, SyncMessageOuterClass.SubscriberOrBuilder> 
          getSubscribersFieldBuilder() {
        if (subscribersBuilder_ == null) {
          subscribersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              SyncMessageOuterClass.Subscriber, SyncMessageOuterClass.Subscriber.Builder, SyncMessageOuterClass.SubscriberOrBuilder>(
                  subscribers_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          subscribers_ = null;
        }
        return subscribersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SyncMessage)
    }

    // @@protoc_insertion_point(class_scope:SyncMessage)
    private static final SyncMessageOuterClass.SyncMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SyncMessageOuterClass.SyncMessage();
    }

    public static SyncMessageOuterClass.SyncMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncMessage>
        PARSER = new com.google.protobuf.AbstractParser<SyncMessage>() {
      @java.lang.Override
      public SyncMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SyncMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SyncMessageOuterClass.SyncMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubscriberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Subscriber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    java.lang.String getNameSurname();
    /**
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    com.google.protobuf.ByteString
        getNameSurnameBytes();

    /**
     * <code>int64 start_date = 3;</code>
     * @return The startDate.
     */
    long getStartDate();

    /**
     * <code>int64 last_accessed = 4;</code>
     * @return The lastAccessed.
     */
    long getLastAccessed();

    /**
     * <code>repeated string interests = 5;</code>
     * @return A list containing the interests.
     */
    java.util.List<java.lang.String>
        getInterestsList();
    /**
     * <code>repeated string interests = 5;</code>
     * @return The count of interests.
     */
    int getInterestsCount();
    /**
     * <code>repeated string interests = 5;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    java.lang.String getInterests(int index);
    /**
     * <code>repeated string interests = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    com.google.protobuf.ByteString
        getInterestsBytes(int index);

    /**
     * <code>bool isOnline = 6;</code>
     * @return The isOnline.
     */
    boolean getIsOnline();

    /**
     * <code>.Subscriber.DemandType demand = 7;</code>
     * @return The enum numeric value on the wire for demand.
     */
    int getDemandValue();
    /**
     * <code>.Subscriber.DemandType demand = 7;</code>
     * @return The demand.
     */
    SyncMessageOuterClass.Subscriber.DemandType getDemand();
  }
  /**
   * Protobuf type {@code Subscriber}
   */
  public static final class Subscriber extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Subscriber)
      SubscriberOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Subscriber.class.getName());
    }
    // Use Subscriber.newBuilder() to construct.
    private Subscriber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Subscriber() {
      nameSurname_ = "";
      interests_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      demand_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SyncMessageOuterClass.internal_static_Subscriber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SyncMessageOuterClass.internal_static_Subscriber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SyncMessageOuterClass.Subscriber.class, SyncMessageOuterClass.Subscriber.Builder.class);
    }

    /**
     * Protobuf enum {@code Subscriber.DemandType}
     */
    public enum DemandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUBS = 0;</code>
       */
      SUBS(0),
      /**
       * <code>ONLN = 1;</code>
       */
      ONLN(1),
      /**
       * <code>OFFL = 2;</code>
       */
      OFFL(2),
      /**
       * <code>DEL = 3;</code>
       */
      DEL(3),
      /**
       * <code>UPDT = 4;</code>
       */
      UPDT(4),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 3,
          /* suffix= */ "",
          DemandType.class.getName());
      }
      /**
       * <code>SUBS = 0;</code>
       */
      public static final int SUBS_VALUE = 0;
      /**
       * <code>ONLN = 1;</code>
       */
      public static final int ONLN_VALUE = 1;
      /**
       * <code>OFFL = 2;</code>
       */
      public static final int OFFL_VALUE = 2;
      /**
       * <code>DEL = 3;</code>
       */
      public static final int DEL_VALUE = 3;
      /**
       * <code>UPDT = 4;</code>
       */
      public static final int UPDT_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DemandType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DemandType forNumber(int value) {
        switch (value) {
          case 0: return SUBS;
          case 1: return ONLN;
          case 2: return OFFL;
          case 3: return DEL;
          case 4: return UPDT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DemandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DemandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DemandType>() {
              public DemandType findValueByNumber(int number) {
                return DemandType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SyncMessageOuterClass.Subscriber.getDescriptor().getEnumTypes().get(0);
      }

      private static final DemandType[] VALUES = values();

      public static DemandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DemandType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Subscriber.DemandType)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_SURNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nameSurname_ = "";
    /**
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    @java.lang.Override
    public java.lang.String getNameSurname() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameSurname_ = s;
        return s;
      }
    }
    /**
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameSurnameBytes() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameSurname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_DATE_FIELD_NUMBER = 3;
    private long startDate_ = 0L;
    /**
     * <code>int64 start_date = 3;</code>
     * @return The startDate.
     */
    @java.lang.Override
    public long getStartDate() {
      return startDate_;
    }

    public static final int LAST_ACCESSED_FIELD_NUMBER = 4;
    private long lastAccessed_ = 0L;
    /**
     * <code>int64 last_accessed = 4;</code>
     * @return The lastAccessed.
     */
    @java.lang.Override
    public long getLastAccessed() {
      return lastAccessed_;
    }

    public static final int INTERESTS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList interests_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string interests = 5;</code>
     * @return A list containing the interests.
     */
    public com.google.protobuf.ProtocolStringList
        getInterestsList() {
      return interests_;
    }
    /**
     * <code>repeated string interests = 5;</code>
     * @return The count of interests.
     */
    public int getInterestsCount() {
      return interests_.size();
    }
    /**
     * <code>repeated string interests = 5;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    public java.lang.String getInterests(int index) {
      return interests_.get(index);
    }
    /**
     * <code>repeated string interests = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    public com.google.protobuf.ByteString
        getInterestsBytes(int index) {
      return interests_.getByteString(index);
    }

    public static final int ISONLINE_FIELD_NUMBER = 6;
    private boolean isOnline_ = false;
    /**
     * <code>bool isOnline = 6;</code>
     * @return The isOnline.
     */
    @java.lang.Override
    public boolean getIsOnline() {
      return isOnline_;
    }

    public static final int DEMAND_FIELD_NUMBER = 7;
    private int demand_ = 0;
    /**
     * <code>.Subscriber.DemandType demand = 7;</code>
     * @return The enum numeric value on the wire for demand.
     */
    @java.lang.Override public int getDemandValue() {
      return demand_;
    }
    /**
     * <code>.Subscriber.DemandType demand = 7;</code>
     * @return The demand.
     */
    @java.lang.Override public SyncMessageOuterClass.Subscriber.DemandType getDemand() {
      SyncMessageOuterClass.Subscriber.DemandType result = SyncMessageOuterClass.Subscriber.DemandType.forNumber(demand_);
      return result == null ? SyncMessageOuterClass.Subscriber.DemandType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, nameSurname_);
      }
      if (startDate_ != 0L) {
        output.writeInt64(3, startDate_);
      }
      if (lastAccessed_ != 0L) {
        output.writeInt64(4, lastAccessed_);
      }
      for (int i = 0; i < interests_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, interests_.getRaw(i));
      }
      if (isOnline_ != false) {
        output.writeBool(6, isOnline_);
      }
      if (demand_ != SyncMessageOuterClass.Subscriber.DemandType.SUBS.getNumber()) {
        output.writeEnum(7, demand_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nameSurname_);
      }
      if (startDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startDate_);
      }
      if (lastAccessed_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastAccessed_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < interests_.size(); i++) {
          dataSize += computeStringSizeNoTag(interests_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInterestsList().size();
      }
      if (isOnline_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isOnline_);
      }
      if (demand_ != SyncMessageOuterClass.Subscriber.DemandType.SUBS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, demand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SyncMessageOuterClass.Subscriber)) {
        return super.equals(obj);
      }
      SyncMessageOuterClass.Subscriber other = (SyncMessageOuterClass.Subscriber) obj;

      if (getId()
          != other.getId()) return false;
      if (!getNameSurname()
          .equals(other.getNameSurname())) return false;
      if (getStartDate()
          != other.getStartDate()) return false;
      if (getLastAccessed()
          != other.getLastAccessed()) return false;
      if (!getInterestsList()
          .equals(other.getInterestsList())) return false;
      if (getIsOnline()
          != other.getIsOnline()) return false;
      if (demand_ != other.demand_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNameSurname().hashCode();
      hash = (37 * hash) + START_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartDate());
      hash = (37 * hash) + LAST_ACCESSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastAccessed());
      if (getInterestsCount() > 0) {
        hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
        hash = (53 * hash) + getInterestsList().hashCode();
      }
      hash = (37 * hash) + ISONLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOnline());
      hash = (37 * hash) + DEMAND_FIELD_NUMBER;
      hash = (53 * hash) + demand_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SyncMessageOuterClass.Subscriber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SyncMessageOuterClass.Subscriber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SyncMessageOuterClass.Subscriber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SyncMessageOuterClass.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SyncMessageOuterClass.Subscriber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Subscriber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Subscriber)
        SyncMessageOuterClass.SubscriberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SyncMessageOuterClass.internal_static_Subscriber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SyncMessageOuterClass.internal_static_Subscriber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SyncMessageOuterClass.Subscriber.class, SyncMessageOuterClass.Subscriber.Builder.class);
      }

      // Construct using SyncMessageOuterClass.Subscriber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        nameSurname_ = "";
        startDate_ = 0L;
        lastAccessed_ = 0L;
        interests_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        isOnline_ = false;
        demand_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SyncMessageOuterClass.internal_static_Subscriber_descriptor;
      }

      @java.lang.Override
      public SyncMessageOuterClass.Subscriber getDefaultInstanceForType() {
        return SyncMessageOuterClass.Subscriber.getDefaultInstance();
      }

      @java.lang.Override
      public SyncMessageOuterClass.Subscriber build() {
        SyncMessageOuterClass.Subscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SyncMessageOuterClass.Subscriber buildPartial() {
        SyncMessageOuterClass.Subscriber result = new SyncMessageOuterClass.Subscriber(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SyncMessageOuterClass.Subscriber result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nameSurname_ = nameSurname_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.startDate_ = startDate_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lastAccessed_ = lastAccessed_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          interests_.makeImmutable();
          result.interests_ = interests_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.isOnline_ = isOnline_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.demand_ = demand_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SyncMessageOuterClass.Subscriber) {
          return mergeFrom((SyncMessageOuterClass.Subscriber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SyncMessageOuterClass.Subscriber other) {
        if (other == SyncMessageOuterClass.Subscriber.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getNameSurname().isEmpty()) {
          nameSurname_ = other.nameSurname_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getStartDate() != 0L) {
          setStartDate(other.getStartDate());
        }
        if (other.getLastAccessed() != 0L) {
          setLastAccessed(other.getLastAccessed());
        }
        if (!other.interests_.isEmpty()) {
          if (interests_.isEmpty()) {
            interests_ = other.interests_;
            bitField0_ |= 0x00000010;
          } else {
            ensureInterestsIsMutable();
            interests_.addAll(other.interests_);
          }
          onChanged();
        }
        if (other.getIsOnline() != false) {
          setIsOnline(other.getIsOnline());
        }
        if (other.demand_ != 0) {
          setDemandValue(other.getDemandValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                nameSurname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                startDate_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                lastAccessed_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureInterestsIsMutable();
                interests_.add(s);
                break;
              } // case 42
              case 48: {
                isOnline_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                demand_ = input.readEnum();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nameSurname_ = "";
      /**
       * <code>string name_surname = 2;</code>
       * @return The nameSurname.
       */
      public java.lang.String getNameSurname() {
        java.lang.Object ref = nameSurname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nameSurname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name_surname = 2;</code>
       * @return The bytes for nameSurname.
       */
      public com.google.protobuf.ByteString
          getNameSurnameBytes() {
        java.lang.Object ref = nameSurname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nameSurname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name_surname = 2;</code>
       * @param value The nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nameSurname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name_surname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameSurname() {
        nameSurname_ = getDefaultInstance().getNameSurname();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name_surname = 2;</code>
       * @param value The bytes for nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nameSurname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long startDate_ ;
      /**
       * <code>int64 start_date = 3;</code>
       * @return The startDate.
       */
      @java.lang.Override
      public long getStartDate() {
        return startDate_;
      }
      /**
       * <code>int64 start_date = 3;</code>
       * @param value The startDate to set.
       * @return This builder for chaining.
       */
      public Builder setStartDate(long value) {

        startDate_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 start_date = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startDate_ = 0L;
        onChanged();
        return this;
      }

      private long lastAccessed_ ;
      /**
       * <code>int64 last_accessed = 4;</code>
       * @return The lastAccessed.
       */
      @java.lang.Override
      public long getLastAccessed() {
        return lastAccessed_;
      }
      /**
       * <code>int64 last_accessed = 4;</code>
       * @param value The lastAccessed to set.
       * @return This builder for chaining.
       */
      public Builder setLastAccessed(long value) {

        lastAccessed_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_accessed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastAccessed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastAccessed_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList interests_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureInterestsIsMutable() {
        if (!interests_.isModifiable()) {
          interests_ = new com.google.protobuf.LazyStringArrayList(interests_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @return A list containing the interests.
       */
      public com.google.protobuf.ProtocolStringList
          getInterestsList() {
        interests_.makeImmutable();
        return interests_;
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @return The count of interests.
       */
      public int getInterestsCount() {
        return interests_.size();
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @param index The index of the element to return.
       * @return The interests at the given index.
       */
      public java.lang.String getInterests(int index) {
        return interests_.get(index);
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the interests at the given index.
       */
      public com.google.protobuf.ByteString
          getInterestsBytes(int index) {
        return interests_.getByteString(index);
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @param index The index to set the value at.
       * @param value The interests to set.
       * @return This builder for chaining.
       */
      public Builder setInterests(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureInterestsIsMutable();
        interests_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @param value The interests to add.
       * @return This builder for chaining.
       */
      public Builder addInterests(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureInterestsIsMutable();
        interests_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @param values The interests to add.
       * @return This builder for chaining.
       */
      public Builder addAllInterests(
          java.lang.Iterable<java.lang.String> values) {
        ensureInterestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, interests_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterests() {
        interests_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string interests = 5;</code>
       * @param value The bytes of the interests to add.
       * @return This builder for chaining.
       */
      public Builder addInterestsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureInterestsIsMutable();
        interests_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private boolean isOnline_ ;
      /**
       * <code>bool isOnline = 6;</code>
       * @return The isOnline.
       */
      @java.lang.Override
      public boolean getIsOnline() {
        return isOnline_;
      }
      /**
       * <code>bool isOnline = 6;</code>
       * @param value The isOnline to set.
       * @return This builder for chaining.
       */
      public Builder setIsOnline(boolean value) {

        isOnline_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bool isOnline = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOnline() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isOnline_ = false;
        onChanged();
        return this;
      }

      private int demand_ = 0;
      /**
       * <code>.Subscriber.DemandType demand = 7;</code>
       * @return The enum numeric value on the wire for demand.
       */
      @java.lang.Override public int getDemandValue() {
        return demand_;
      }
      /**
       * <code>.Subscriber.DemandType demand = 7;</code>
       * @param value The enum numeric value on the wire for demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemandValue(int value) {
        demand_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.Subscriber.DemandType demand = 7;</code>
       * @return The demand.
       */
      @java.lang.Override
      public SyncMessageOuterClass.Subscriber.DemandType getDemand() {
        SyncMessageOuterClass.Subscriber.DemandType result = SyncMessageOuterClass.Subscriber.DemandType.forNumber(demand_);
        return result == null ? SyncMessageOuterClass.Subscriber.DemandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Subscriber.DemandType demand = 7;</code>
       * @param value The demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemand(SyncMessageOuterClass.Subscriber.DemandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        demand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Subscriber.DemandType demand = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDemand() {
        bitField0_ = (bitField0_ & ~0x00000040);
        demand_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Subscriber)
    }

    // @@protoc_insertion_point(class_scope:Subscriber)
    private static final SyncMessageOuterClass.Subscriber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SyncMessageOuterClass.Subscriber();
    }

    public static SyncMessageOuterClass.Subscriber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscriber>
        PARSER = new com.google.protobuf.AbstractParser<Subscriber>() {
      @java.lang.Override
      public Subscriber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscriber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscriber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SyncMessageOuterClass.Subscriber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SyncMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Subscriber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Subscriber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SyncMessage.proto\"B\n\013SyncMessage\022\021\n\tse" +
      "rver_id\030\001 \001(\005\022 \n\013subscribers\030\002 \003(\0132\013.Sub" +
      "scriber\"\345\001\n\nSubscriber\022\n\n\002id\030\001 \001(\005\022\024\n\014na" +
      "me_surname\030\002 \001(\t\022\022\n\nstart_date\030\003 \001(\003\022\025\n\r" +
      "last_accessed\030\004 \001(\003\022\021\n\tinterests\030\005 \003(\t\022\020" +
      "\n\010isOnline\030\006 \001(\010\022&\n\006demand\030\007 \001(\0162\026.Subsc" +
      "riber.DemandType\"=\n\nDemandType\022\010\n\004SUBS\020\000" +
      "\022\010\n\004ONLN\020\001\022\010\n\004OFFL\020\002\022\007\n\003DEL\020\003\022\010\n\004UPDT\020\004b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SyncMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SyncMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SyncMessage_descriptor,
        new java.lang.String[] { "ServerId", "Subscribers", });
    internal_static_Subscriber_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Subscriber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Subscriber_descriptor,
        new java.lang.String[] { "Id", "NameSurname", "StartDate", "LastAccessed", "Interests", "IsOnline", "Demand", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
